### ISSUE TITLE
大佬个人版限制太多了,啥都无法体验,放宽一点权限吧!比如最高添加10-20个IP也行啊!

### ISSUE THREAD

**Issue by kenuoseclab** [0xbug/Biu#10]
大佬个人版限制太多了,啥都无法体验,放宽一点权限吧!比如最高添加10-20个IP也行啊!个人版登陆进去添加好目标啥功能都无法体验,也无法查看

**Comment by 0xbug** [comment]
看了一下因为你探测的资产没有开放端口 所以才啥功能都没有

**Comment by kenuoseclab** [comment]
> 看了一下因为你探测的资产没有开放端口 所以才啥功能都没有

好吧!我随便丢的一个进去测试

**Comment by ZFYy1x** [comment]
老哥可以邀请我注册嘛？

**Comment by HHhne** [comment]
大哥们，求一个邀请码
maryettaloperfidoalf77@gmail.com

**Comment by Fanc1er** [comment]
96b80e3b0ba7a975@protonmail.com

**Comment by Fanc1er** [comment]
老哥,求一个邀请码. 96b80e3b0ba7a975@protonmail.com
